### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brianjolney** [ahoereth/wordpress-kudos#1]
Warning: Missing argument 2 for get_kudos() etc....

Using <?php kudos(); ?> just after <?php the_content(); ?>

Wordpress 3.5.2

The button shows up properly right below the error message.

Full error message:

Warning: Missing argument 2 for get_kudos(), called in /var/www/......./wp-content/plugins/kudos/php/functions.php on line 120 and defined in /var/www/......./wp-content/plugins/kudos/php/functions.php on line 69 Warning: extract() expects parameter 1 to be array, null given in /var/www/......./wp-content/plugins/kudos/php/functions.php on line 70

**Comment by ahoereth** [comment]
Sorry for the late fix.
